import upperSnakeCaseToSentenceCase from "@/utils/upper-snake-case-to-sentence-case";
import axios from "axios";
import moment from "moment/moment";

const apiInstance = axios.create({
  baseURL: "https://api.veevotech.com",
});

export const sendSMS = ({ phone, message }) => {
  apiInstance
    .get("/sendsms", {
      params: new URLSearchParams({
        hash: "8bded5bd3030142dbb0e164fe1faafae",
        receivernum: phone,
        textmessage: message,
        sendernum: "8583",
      }),
    })
    .then((res) => {
      console.log("+ SMS Sent", res.data);
    })
    .catch((err) => {
      console.log("- SMS Error", err);
    });
};

export const composeAccountCreationSMS = ({ firstName, password, role }) =>
  `\n\nGreetings ${firstName},\n\nYou have been registered for a ${upperSnakeCaseToSentenceCase(
    role
  )} account on ${moment(new Date()).format(
    "LLL"
  )}.\n\nYour autogenerated password for the app is:\n\n${password}\n\nPlease make sure not to share it, and change this password at your earliest.\n\nTeam,\nEziqaat`;

export const composeResetPasswordSMS = ({ password }) =>
  `\n\nGreetings,\n\nYour password was reset at ${moment(new Date()).format(
    "LLL"
  )}. Your new autogenerated password is:\n\n${password}\n\nPlease make sure not to share it, and change this password at your earliest.\n\nTeam,\nEziqaat`;
