import getEnv from "@/config/get-env";
import upperSnakeCaseToSentenceCase from "@/utils/upper-snake-case-to-sentence-case";
import axios from "axios";
import moment from "moment/moment";

const apiInstance = axios.create({
  baseURL: "https://api.veevotech.com",
});

export const sendSMS = ({ phone, message }) => {
  apiInstance
    .get("/sendsms", {
      params: new URLSearchParams({
        hash: getEnv("SMS_API_KEY"),
        receivernum: phone,
        textmessage: message,
        sendernum: "8583",
      }),
    })
    .then((res) => {
      console.log("+ SMS Sent", res.data);
    })
    .catch((err) => {
      console.log("- SMS Error", err);
    });
};

export const composeAccountCreationSMS = ({ firstName, password, role }) =>
  `\n\nGreetings ${firstName},\n\nYou have been registered for a ${upperSnakeCaseToSentenceCase(
    role
  )} account on ${moment(new Date()).format(
    "LLL"
  )}.\n\nYour autogenerated password for the app is:\n\n${password}\n\nPlease make sure not to share it, and change this password at your earliest.\n\nTeam,\nEziqaat`;

export const composeResetPasswordSMS = ({ password }) =>
  `\n\nGreetings,\n\nYour password was reset at ${moment(new Date()).format(
    "LLL"
  )}. Your new autogenerated password is:\n\n${password}\n\nPlease make sure not to share it, and change this password at your earliest.\n\nTeam,\nEziqaat`;

export const composeCollectionSMS = ({
  id,
  amount,
  address,
  workerName,
  workerId,
  areaName,
  chairpersonPhone,
}) =>
  `\n\nGreetings,\n\nYour donation of PKR ${Intl.NumberFormat("en-US").format(
    amount
  )} has been collected by our worker ${workerName} (ID: ${workerId}) from the provided address: ${address} (${areaName}) on ${moment(
    new Date()
  ).format(
    "LLL"
  )}. \n\nYour donation ID is ${id}. \n\nFor any information, contact the chairperson of ${areaName} at ${chairpersonPhone} \n\nTeam,\nEziqaat`;
