const { getEnv } = require("../config");
const axios = require("axios");
const { upperSnakeCaseToSentenceCase } = require("../utils");
const moment = require("moment");

/**
 * Create an API instance pointing to Veevo Tech SMS
 * Tool, with API hash
 */
const apiInstance = axios.create({
  baseURL: "https://api.veevotech.com",
});

/**
 * Function that sends message to a valid phone number
 * @param {{ phone: string; message: string; }} options
 */
module.exports.sendSMS = ({ phone, message }) => {
  apiInstance
    .get("/sendsms", {
      params: new URLSearchParams({
        hash: getEnv("SMS_API_KEY"),
        receivernum: phone,
        textmessage: message,
        sendernum: "8583",
      }),
    })
    .then((res) => {
      console.log("+ SMS Sent", res.data);
    })
    .catch((err) => {
      console.log("- SMS Error", err);
    });
};

module.exports.composeAccountCreationSMS = ({ firstName, password, role }) =>
  `\n\nGreetings ${firstName},\n\nYou have been registered for a ${upperSnakeCaseToSentenceCase(
    role
  )} account on ${moment(new Date()).format(
    "LLL"
  )}.\n\nYour autogenerated password for the app is:\n\n${password}\n\nPlease make sure not to share it, and change this password at your earliest.\n\nTeam,\nEziqaat`;

module.exports.composeResetPasswordSMS = ({ password }) =>
  `\n\nGreetings,\n\nYour password was reset at ${moment(new Date()).format(
    "LLL"
  )}. Your new autogenerated password is:\n\n${password}\n\nPlease make sure not to share it, and change this password at your earliest.\n\nTeam,\nEziqaat`;

module.exports.composeCollectionSMS = ({
  id,
  amount,
  address,
  workerName,
  workerId,
  areaName,
  chairpersonPhone,
}) =>
  `\n\nGreetings,\n\nYour donation of PKR ${Intl.NumberFormat("en-US").format(
    amount
  )} has been collected by our worker ${workerName} (ID: ${workerId}) = require( the provided address: ${address} (${areaName}) on ${moment(
    new Date()
  ).format(
    "LLL"
  )}. \n\nYour donation ID is ${id}. \n\nFor any information, contact the chairperson of ${areaName} at ${chairpersonPhone} \n\nTeam,\nEziqaat`;
