import upperSnakeCaseToSentenceCase from "@/utils/upper-snake-case-to-sentence-case";
import moment from "moment";
import { Resend } from "resend";

const resend = new Resend("re_WNUXVbuC_CFF92wHkcrfJoPeBjPYjpjVx");

export const sendEmail = ({ to, subject, html }) => {
  resend.emails
    .send({
      from: "onboarding@resend.dev",
      to,
      subject,
      html,
    })
    .then((res) => {
      console.log("+ Email id:", res.id);
    })
    .catch((err) => {
      console.log("- Email Error:", err);
    });
};

export const composeAccountCreationEmail = ({ firstName, password, role }) =>
  `\n\nGreetings ${firstName},\n\nYou have been registered for a ${upperSnakeCaseToSentenceCase(
    role
  )} account on ${moment(new Date()).format(
    "LLL"
  )}.\n\nYour autogenerated password for the app is:\n\n${password}\n\nPlease make sure not to share it, and change this password at your earliest.\n\nTeam,\nZakatify`;
